name: AI-Based Architecture Generator
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

     # 3. Run JArchitect analysis
      - name: Run JArchitect analysis
        run: |
          curl -L https://download.jarchitect.com/jarchitect-cli-latest.zip -o jarchitect.zip
          unzip jarchitect.zip
          ./jarchitect-cli/bin/jarchitect --analyze --project your-java-project-directory

      # 4. Generate architecture diagram
      - name: Generate architecture diagram
        run: |
          ./jarchitect-cli/bin/jarchitect --generate-diagrams

      # 5. Upload JArchitect reports (Architecture diagrams and other analysis reports)
      - name: Upload JArchitect reports
        uses: actions/upload-artifact@v4
        with:
          name: jarchitect-reports
          path: ./reports/

      # 6. Download ThreatAgile tool
      - name: Download ThreatAgile
        run: |
          curl -L https://github.com/threagile/threagile/releases/latest/download/threagile-linux -o threagile
          chmod +x threagile

      # 7. Run ThreatAgile to perform threat modeling
      - name: Run ThreatAgile analysis
        run: |
          ./threagile --input ./reports/architecture.yaml --output ./threagile-reports/

      # 8. Upload ThreatAgile threat reports
      - name: Upload ThreatAgile threat reports
        uses: actions/upload-artifact@v4
        with:
          name: threagile-reports
          path: ./threagile-reports/
