name: AI-Based Architecture Generator
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Download JavaParser JAR
        run: |
          curl -L https://repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.25.4/javaparser-core-3.25.4.jar -o javaparser-core.jar

      # 4. Run JavaParser to parse the Java code and generate architecture.yaml
      - name: Generate architecture.yaml using JavaParser
        run: |
          java -cp javaparser-core.jar com.github.javaparser.StaticJavaParser parse src/**/*.java > architecture.yaml
          
      # 5. Download Threagile
      - name: Download Threagile
        run: |
          curl -L https://github.com/threagile/threagile/releases/latest/download/threagile-linux -o threagile
          chmod +x threagile

      # 6. Run Threagile on the generated architecture.yaml
      - name: Run Threagile
        run: |
          ./threagile --input architecture.yaml --output output/

      # 7. Upload the generated threat report
      - name: Upload Threat Report
        uses: actions/upload-artifact@v4
        with:
          name: threagile-report
          path: output/
