name: AI-Based Architecture Generator
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Extract file structure (for context)
        run: |
          tree -J -L 3 > structure.json
          find . -name "*.java" | xargs cat > all_java_code.txt

      - name: Generate architecture using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          REQUEST=$(jq -n --arg code "$(head -c 30000 all_java_code.txt)" --arg structure "$(cat structure.json)" '{
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "You are a software architect."},
              {"role": "user", "content": "Based on this Java project structure and code, generate an architecture.md file and a PlantUML diagram.\n\nStructure:\n\($structure)\n\nCode:\n\($code)"}
            ]
          }')

          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$REQUEST")

          echo "$RESPONSE" | jq -r '.choices[0].message.content' > ai_output.md

      - name: Debug:Show AI output
        run: cat ai_output.md

      - name: Extract architecture.md
        run: |
          awk '!/```plantuml/,/```plantuml/' ai_output.md > architecture.md || true

      - name: Extract diagram.puml from AI output
        run: |
          awk '/```plantuml/,/```/ { if (!/```/) print }' ai_output.md > diagram.puml

      - name: Fallback dummy diagram if AI fails
        run: |
          if ! grep -q "@startuml" diagram.puml; then
            echo "@startuml\nAlice -> Bob: Test\n@enduml" > diagram.puml
          fi

      - name: Debug: Show diagram.puml content
        run: cat diagram.puml

      - name: Generate diagram using PlantUML Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace plantuml/plantuml -tpng diagram.puml

      - name: List files after generation
        run: ls -al

      - name: Upload diagram as artifact
        uses: actions/upload-artifact@v4
        with:
          name: architecture-diagram
          path: diagram.png
