    name: OWASP ZAP Security Scan
    on: [push]
    jobs:
      zap_scan:
        runs-on: ubuntu-latest
        name: Run DAST scan on the web application
        steps:
        - name: Checkout source code
          uses: actions/checkout@v3
        - name: Run OWASP ZAP scan
          uses: zaproxy/action-baseline@v0.6.1
          with:
           docker_name: 'zaproxy/zap-stable'
           target: http://localhost:8080/onlinebookstore/
           rules_file_name: '.zap/rules.tsv'
           cmd_options: '-a'
